### ISSUE TITLE
アスタリスク(*)を使えるようにする

### ISSUE THREAD

**Issue by master-of-sugar** [typesafe-query/typesafe-query#10]
`count(*)`  `table1.*` など

**Comment by master-of-sugar** [comment]
```
Customer_.ALL

Customer_.ASTERISK
```

どっちがいい？

**Comment by master-of-sugar** [comment]
メタジェネレーターですべてのメタクラスに定義しておく

**Comment by shohei-nozaki** [comment]
ALLは予約語だけど普通にフィールド名に使う人いそうだから`Customer_.ASTERISK`にします

**Comment by master-of-sugar** [comment]
`Customer_.ALL_COLUMNS` という選択肢もある

**Comment by master-of-sugar** [comment]
それだとアスタリスクっぽくないか(´・ω・`)

**Comment by shohei-nozaki** [comment]
アスタリスクっぽさで言うと`ASTERISK`が群を抜いてますね、間違いない

**Comment by shohei-nozaki** [comment]
MySQLで試したら`select count(table.*)`は怒られちゃう問題発生
`select table.*` はOK
考えてみりゃそりゃそうか。
