### ISSUE TITLE
クエリの結果をクラス指定せずにMap<>で取得したい

### ISSUE THREAD

**Issue by shohei-nozaki** [typesafe-query/typesafe-query#108]
項目少ない時はクラス定義せずにこんな感じで取りたくもなりませんかね。

```
Map<String, Long> result =
select(Screens.ID, count(Screens.ASTERISK))
.from(Screens.TABLE)
.forOnce()
.getResult();

// 列名指定で取得
Long id= (Long)result.get("id");
```

**Comment by master-of-sugar** [comment]
型パラメーターむちゃくちゃやんｗ

でも `Map` はいやだなあ。全員それ使いよるからなあ。。

**Comment by master-of-sugar** [comment]
ひっそり[こんなやつ](https://github.com/typesafe-query/typesafe-query/blob/master/typesafe-query-core/src/main/java/com/github/typesafe_query/jdbc/mapper/MapResultMapper.java)はいるんだけどねｗ

**Comment by shohei-nozaki** [comment]
いたーーー！！！ｗ
一旦Closeですねｗ
