### ISSUE TITLE
カラムの計算ができるようにする

### ISSUE THREAD

**Issue by master-of-sugar** [typesafe-query/typesafe-query#13]
- 数値の+-*/
- 日付の+-

特に日付がDBMSによってかなり違うので要検討

**Comment by shohei-nozaki** [comment]
日付の加減に関してはDB2だけ`INTERVAL`がいらないらしい。。
もしDB2でINTERVALつけて使えるなら一旦この構文で実装したい。
`select current_date + INTERVAL 1 month;`

##### 【MySql】

```
select current_date + INTERVAL 1 month;
```

参考
http://webmaster.chielog.com/sql/100.html

##### 【DB2】

```
select current_date + 1 month 
```

参考
http://d.hatena.ne.jp/htada/20070528/1180342512

##### 【Oracle】

```
select current_date + INTERVAL '10' MONTH
```

参考
http://www.shift-the-oracle.com/sql/functions/add_months.html

**Comment by shohei-nozaki** [comment]
`日付列 INTERVAL 数値　単位`

この`単位`がDBでバラバラ問題

【MySQL】
http://dev.mysql.com/doc/refman/5.6/ja/date-and-time-functions.html#function_date-add

```
MICROSECOND
SECOND
MINUTE
HOUR
DAY
WEEK
MONTH
QUARTER
YEAR
SECOND_MICROSECOND
MINUTE_MICROSECOND
MINUTE_SECOND
HOUR_MICROSECOND
HOUR_SECOND
HOUR_MINUTE
DAY_MICROSECOND
DAY_SECOND
DAY_MINUTE
DAY_HOUR
YEAR_MONTH
```

【Oracle】
http://www.shift-the-oracle.com/element/literal-datetime-interval.html

```
YEAR
MONTH
DAY
HOUR
MINUTE
SECOND
```
