### ISSUE TITLE
NamedQueryという名前をやめる

### ISSUE THREAD

**Issue by master-of-sugar** [typesafe-query/typesafe-query#22]
JPAのやつと間違えるので。

**Comment by master-of-sugar** [comment]
`stringQueryFrom(String fileName)` はどうだろう？

**Comment by master-of-sugar** [comment]
受ける型は `StringQuery` で統一

**Comment by shohei-nozaki** [comment]
StringQuery→Query
じゃダメですか？

**Comment by master-of-sugar** [comment]
それはちょっと思った。

**Comment by shohei-nozaki** [comment]
別のと名前ダブりそうだしファイル取り込みってパッと見でわかるように的な思惑ですかね？

**Comment by master-of-sugar** [comment]
ファイル名なのか直接SQLなのかはわかるようにしたい

**Comment by master-of-sugar** [comment]
- `Q#namedQuery` => Deprecated
- `Q#stringQuery` => Deprecated
- 追加 => `@#query`
- 追加 => `Q#queryFrom`
- `NamedQuery` => Deprecated
- `StringQuery` => `Query`

**Comment by shohei-nozaki** [comment]
いえすいえす

**Comment by master-of-sugar** [comment]
`NamedQuery` 廃止しようと思ったけど、実はこいつ `getName()` って名前があってログなんかに出したくて作ったの思い出した。**今は全然ログに出してないけど！**

**Comment by master-of-sugar** [comment]
`NamedQuery` => `ResourceQuery` にして活かしてみる作戦

**Comment by master-of-sugar** [comment]
`StringQuery` => `Query` にしようと思ったけどJPAの `Query` と間違えそうだし、一番抽象化されてるみたいなイメージになっちゃうのでそのままにします。
