### ISSUE TITLE
カラムにeqOrIsNullメソッドを追加する

### ISSUE THREAD

**Issue by master-of-sugar** [typesafe-query/typesafe-query#72]
`c.eq(null)` のときは条件式が追加されない仕様。
`c.eqOrIsNull(null)` のときは `c is null` が追加されるように。

**Comment by master-of-sugar** [comment]
`eqOrIsNull`
`eqOrNull`
`eqon`
`eqn`

**Comment by nozakki** [comment]
なんやかんや考えた結果`or(c.eq(null), c.isNull())`って明確に書いてもらったほうがいい気がしてきました。SQLっぽい

**Comment by nozakki** [comment]
`c.in(hoge)` hoge != nullの場合は `c = hogeの値`。hoge == nullの場合は `c is null` に切り替えないといけない

サブクエリ、パラメータ、列を渡された時はnullか判断つかないから対応しない

**Comment by shohei-nozaki** [comment]
なんやかんや考えた結果`or(c.eq(null), c.isNull())`って明確に書いてもらったほうがいい気がしてきました。SQLっぽい
